'use client';
import './globals.css'
import Navbar from "../components/Navbar"
import {SessionProvider} from "next-auth/react";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <SessionProvider>
        <Navbar />
        {children}
        </SessionProvider>
      </body>
    </html>
  )
}
